socialNetworkCode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('socialNetworkCode/',include(('system.urls',"system"),namespace='socialNetworkCode')),
]

system/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_site, name='login'),
    path('logout/', views.logout_site, name='logout'),
    path('demo/<int:eventpage>/<int:peoplepage>', views.demo, name='demo'),
    path('search/', views.search, name='search'),
    path('relationextraction', views.relationextraction, name='relationextraction'),
    path('fileUpload', views.fileUpload, name='fileUpload'),
    path('peoplenews/<str:name>', views.peoplenews, name='peoplenews'),
    path('sin_analysis/<str:name>', views.sin_analysis, name='sin_analysis'),
    path('all_analysis/<str:name>', views.all_analysis, name='all_analysis'),
    path('gn/<str:name>', views.gn, name='gn'),
    path('newgn', views.newgn, name='newgn'),
    path('allgn', views.allgn, name='allgn'),

    path('recommendation/<str:name>', views.recommendation, name='recommendation'),

    path('media_focus/<str:media>/<str:account>', views.media_focus, name='media_focus'),
    path('person_contrast/<str:name>/<str:contrast>', views.person_contrast, name='person_contrast'),
    path('friend_circle/<str:name>', views.friend_circle, name='friend_circle'),

    path('gn_part/<str:name>', views.gn_part, name='gn_part'),
    path('all_gn', views.all_gn, name='all_gn'),

    path('param_gender/<str:name>', views.param_gender, name='param_gender'),
    # path('gn_part/<str:name>', views.gn_part, name='gn_part'),

    path('person_tweet/<int:id_tweet>/<str:name>', views.person_tweet, name='person_tweet'),
    path('person_event/<str:event>/<str:name>', views.person_event, name='person_event'),
    path('sensitiveinfo/<str:event>', views.sensitiveinfo, name='sensitiveinfo'),
    path('sensitive_develop/<str:event>', views.sensitive_develop, name='sensitive_develop'),
    path('tweet_analysis/<int:id_tweet>', views.tweet_analysis, name='tweet_analysis'),

]

templates/MediaFocus.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/main_demo.css' %}">
<title>天鹰监测系统</title>
</head>
<body>
<div style="width: 1300px;margin: auto;">
    <header style="background-color: #547ca5;height: 100px;vertical-align: center;">
        <img src="/static/img/eagle.jpg" height="100px" width="120px">
        <h2 style="text-align: center;margin-top: -60px;">天鹰监测系统</h2>
        <span style="position:relative;float: right;bottom: 30px;right: 20px;">
        <a href="#" style="color: black;" >{{ user.username }}<span class="caret"></span></a>
        <span ><a href="{% url 'socialNetworkCode:logout' %}" style="color: black;" >Logout</a></span>
        </span>
    </header>
        <br><br>
    <div class="navigate" style="float: left;background-color: #F9FAFB;">
        <ul class="">
            <li><a href="{% url 'socialNetworkCode:demo'  1 1 %}" ><b>信息概况监测</b></a></li>
            <h3 style="text-align: center;">{{ name }}</h3>
            <li><a href="{% url 'socialNetworkCode:all_analysis'  name  %}" style="background-color:  #ecf5ff">社交账户</a></li>
        </ul>
    </div>
    <div class="content" style="float: left;margin-left: 20px;">
        <h1>媒体：{{ account.media }}</h1>
        <h3>账号：{{ account.username }}</h3>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">账号基本信息</h3>
            <table class="table" style="width: 900px;">
              <thead>
                <tr><th >用户头像</th>
                    <th >用户名</th>
                    <th>创建时间</th>
                    <th>关注人数</th>
                    <th>被关注人数</th>
                    <th>推文数量</th>
              </tr></thead>
              <tbody>
                <tr>
                  <td><img src="{% static  account.headportrait %} " height="40px" width="60px" ></td>
                  <td >{{ account.username }}</td>
                  <td>{{ account.createtime }}</td>
                  <td>{{ account.follownumber }}</td>
                  <td>{{ account.fansnumber }}</td>
                  <td>{{ account.tweetsnumber }}</td>
                </tr>
              </tbody>
                </table>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">推文</h3>
            <table class="table" style="width: 900px;">
              <thead>
                <tr><th >发文</th>
                    <th >关键词</th>
                    <th >内容模式</th>
                    <th >时间</th>
              </tr></thead>
                <tbody>
                    {% for message in tweet %}
                <tr>
                    <td ><a href="#">{{ message.tweets }}</a></td>
                  <td>{{ message.keywords|safe }}</td>
                  <td>{{ message.contextrange }}</td>
                  <td>{{ message.time }}</td>
                </tr>
                    {% endfor %}
              </tbody>
                </table>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">推文内容比例</h3>
            <div id="main" style="height:400px;width:500px;margin:auto;"></div>

    </div>
</div>
</body>
<script src="{% static 'js/echarts.js' %}"></script>
<script src="{% static 'js/jquery-2.1.0.js' %}"></script>
<script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '图片、视频、文本所占比例',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                x: 'left',
                data: ['图片', '视频', '文本']
            },
            toolbox: {
                show: true,
                feature: {
                    mark: {show: true},
                    dataView: {show: true, readOnly: false},
                    magicType: {
                        show: true,
                        type: ['pie', 'funnel'],
                        option: {
                            funnel: {
                                x: '25%',
                                width: '50%',
                                funnelAlign: 'left',
                                max: 1548
                            }
                        }
                    },
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            calculable: true,
            series: [{
                name: '数量比例',
                type: 'pie',
                radius: "55%",
                center: ["50%", "60%"],
                data: [
                    {value: 335, name: '图片'},
                    {value: 100, name: '文本'},
                    {value: 400, name: '视频'}
                ]
            }
            ]
        };
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

    </script>
</html>

templates/login.html
<!DOCTYPE html >
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'css/mobi.css' %}">
</head>
<body>
<!-- html中的登录表单-->
<div style="position: absolute;left: 40%;top: 25%;width:300px;height:350px;">
    <div style="text-align: center;"><img src="{%  static  'img/eagle.jpg' %} " style="width: 150px;"></div>
<form   method="post" action="{% url 'socialNetworkCode:login' %}">
    {% csrf_token %}
{#    <div style="margin-left: 40%;margin-top: 15%">#}
    <h4  style="text-align: center;">天鹰监测系统</h4>
    <input name="username"  placeholder="账户名"  autocomplete="off" style="margin-top: 30px;width: 300px;height: 35px;border-radius:3px;outline: 0;border-width: 1px;"><br>
    <input name="password" type="password"  placeholder="账户密码"  style="margin-top: 10px;width: 300px;height: 35px;border-radius:3px;outline: 0;border-width: 1px;">

    <button class="btn btn-lg btn-primary btn-block" type="submit" style="width: 300px;">登录</button>
    <span style="color: red" >{{ login_err }}</span>
{#    </div>#}
</form>
</div>
</body>
</html>

templates/peoplenews.html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/main_demo.css' %}">
<title>天鹰监测系统</title>
</head>
<body>
<div style="width: 1300px;margin: auto;">
    <header style="background-color: #547ca5;height: 100px;vertical-align: center;">
        <img src="/static/img/eagle.jpg" height="100px" width="120px">
        <h2 style="text-align: center;margin-top: -60px;">天鹰监测系统</h2>
        <span style="position:relative;float: right;bottom: 30px;right: 20px;">
        <a href="#" style="color: black;" >{{ user.username }}<span class="caret"></span></a>
        <span ><a href="{% url 'socialNetworkCode:logout' %}" style="color: black;" >Logout</a></span>
        </span>
    </header>
        <br><br>

    <div class="navigate" style="float: left;background-color: #F9FAFB;">
        <ul class="">
            <li><a href="{% url 'socialNetworkCode:demo'  1 1 %}" ><b>信息概况监测</b></a></li>
            <h3 style="text-align: center;">{{ name }}</h3>
            <li><a href="{% url 'socialNetworkCode:peoplenews'  name  %}" style="background-color:  #ecf5ff" >人物介绍</a></li>
            <li><a href="{% url 'socialNetworkCode:all_analysis'  name  %}" >人物整体分析</a></li>
            <li><a href="{% url 'socialNetworkCode:sin_analysis'  name  %}"  >人物单体分析</a></li>
        </ul>
    </div>
    <div class="content" style="float: left;margin-left: 20px;">
        <div class="basic_info">
            <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">基本信息</h3>
                <h3 >{{ name }}<img src="{% static user.photo %}" height="60px" width="100px" style="float: left;"></h3>
            <br><br><b>标签：</b>
                {% for label in labels  %}<span style="border: 1px solid #4183C4;margin-left:30px;padding: 2px 20px;border-radius: 8px;">{{ label.label }}</span>{% endfor %}
                <p style="width: 1000px;margin-left: 20px;">{{ user.introduction|safe}}</p></div>
            <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">生平经历</h3>
                <table class="table" style="width:900px;margin-left: 50px">
                <thead><tr><th >日期</th>
                <th >经历</th></tr></thead>
                <tbody>
                {% for message in lives %}
                <tr><td >{{ message.time }}</td>
                <td>{{ message.introduction }}</td></tr>
                {% endfor %}
                </tbody>
                </table>
            <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">人物言论</h3>
                <table class="table" style="width: 900px;margin-left: 50px">
                <thead>
                <tr><th >时间</th>
                <th >主要言论</th>
                <th >言论来源</th>
                </tr></thead>
                <tbody>
                {% for message in words %}
                <tr>
                <td >{{ message.time }}</td>
                <td>{{ message.userspeech }}</td>
                <td>{{ message.speechsource }}</td>
                </tr>
                {% endfor %}
                </tbody>
                </table>
            <br><br>

</div>
  </div>


</body>
<script type="text/javascript" src="{% static 'js/jquery-2.1.0.js' %}"></script>
<script src="{% static 'js/echarts.js' %}"></script>

<script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '人物活动趋势'
            },
            tooltip: {
				trigger:'axis'
				},
            legend: {
                data:['活动趋势']
            },
			toolbox: {
        		show : true,
        		feature : {
           			mark : {show: true},
            		dataView : {show: true, readOnly: false},
            		magicType : {show: true, type: ['line', 'bar']},
            		restore : {show: true},
            		saveAsImage : {show: true}
        		}
    		},
			calculable:true,
            xAxis: {
				type:'category',
				boundaryGap:false,
                data: ['2018-1-1','2018-1-2','2018-1-3','2018-1-4','2018-1-5','2018-1-6','2018-1-7','2018-1-8']
            },
            yAxis: {
				type:'value'
				},
            series: [{
                name: '影响指数',
                type: 'line',
                data: [100,200,300,266,400,190,875,766],
				markPoint:{
					data:[
						{type:'max',name:'最大值'},
						{type:'min',name:'最小值'}
					]
					}
            },
			]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>

</html>

templates/person_contrast.html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/main_demo.css' %}">
<title>天鹰监测系统</title>
</head>
<body>
<div style="width: 1300px;margin: auto;">
    <header style="background-color: #547ca5;height: 100px;vertical-align: center;">
        <img src="/static/img/eagle.jpg" height="100px" width="120px">
        <h2 style="text-align: center;margin-top: -60px;">天鹰监测系统</h2>
        <span style="position:relative;float: right;bottom: 30px;right: 20px;">
        <a href="#" style="color: black;" >{{ user.username }}<span class="caret"></span></a>
        <span ><a href="{% url 'socialNetworkCode:logout' %}" style="color: black;" >Logout</a></span>
        </span>
    </header>
        <br><br>
    <div class="navigate" style="float: left;background-color: #F9FAFB;">
        <ul class="">
            <li><a href="{% url 'socialNetworkCode:demo'  1 1 %}" ><b>信息概况监测</b></a></li>
            <h3 style="text-align: center;">{{ name }}</h3>
            <li><a href="{% url 'socialNetworkCode:sin_analysis'  name  %}" style="background-color:  #ecf5ff">人物对比</a></li>
        </ul>
    </div>
    <div class="content" style="float: left;margin-left: 20px;">
        <div style="width: 450px;display: inline-block;border-right: solid gray 1px; ">
             <h3 >{{ person.name }}<img src="{% static person.photo %}" height="60px" width="100px" style="float: left;"></h3>
            <br><br><b>标签：</b>
            {% for label in person_labels  %}<span style="border: 1px solid #4183C4;margin-left:30px;padding: 2px 20px;border-radius: 8px;">{{ label.label }}</span>{% endfor %}
            <p style="width: 450px;height: 249px;">{{ person.introduction|safe}}</p>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">参与事件</h3>
            <div style="height: 249px">
            <table class="table"  style="width: 400px;">
            <thead>
            <tr><th >参与事件</th>
                </tr></thead>
                <tbody>
                {% for info in person_events %}
            <tr>
                <td><a href="{% url 'socialNetworkCode:person_event' info.event name %}">{{ info.event }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
            </div>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">言论词云</h3>
            <div id="main1" style="height:400px; width:450px;"></div>

        </div>

        <div style="width: 450px;display: inline-block;margin-left: 20px;vertical-align: top;">
             <h3 >{{ contrast.name }}<img src="{% static contrast.photo %}" height="60px" width="100px" style="float: left;"></h3>
            <button class="addbutton" style="margin: -6px 100px;color:white;background-color:blue;width: 70px;height: 30px;border: 0;">添加人物</button>
            <br><br><b>标签：</b>
            {% for label in contrast_labels  %}<span style="border: 1px solid #4183C4;margin-left:30px;padding: 2px 20px;border-radius: 8px;">{{ label.label }}</span>{% endfor %}
            <p style="width: 450px;margin-left: 20px;height: 249px;">{{ contrast.introduction|safe}}</p>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">参与事件</h3>
            <div style="height:249px;">
            <table class="table"  style="width: 400px;">
            <thead>
            <tr><th >参与事件</th>
                </tr></thead>
                <tbody>
                {% for info in contrast_events %}
            <tr>
                <td><a href="{% url 'socialNetworkCode:person_event' info.event name %}">{{ info.event }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
            </div>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">言论词云</h3>
            <div id="main2" style="height:400px; width:450px;"></div>

        </div>

        <div >
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">同时出现</h3>
            两人同时出现55次。
            <div id="main3" style="height:500px; width:700px;margin: auto;"></div>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;">两人分析</h3>
            <b>{{ person.name }}和{{ contrast.name }}相似度为90%，是同一类人，具有港独，反共倾向。</b><br><br><br>
        </div>
    </div>
</div>
</body>
<script src="{% static 'js/echarts.js' %}"></script>
<script src="{% static 'js/jquery-2.1.0.js' %}"></script>
<script src="{% static 'js/echarts-wordcloud.js' %}"></script>
<script>
     $(document).ready(function () {
         $(".addbutton").click(function () {
            $.ajax({
            //几个参数需要注意一下
                type: "POST",//方法类型
                dataType: "json",//预期服务器返回的数据类型
                url: "{% url 'socialNetworkCode:person_contrast' name contrast.name %}?name="+"{{ contrast.name }}"//url
         });
     })})
</script>
<script>
    var myChart = echarts.init(document.getElementById('main1'));
option = {
    title:{
        text:"词云图",
        x:'center',
    },
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 20,
        sizeRange: [12, 50],
        rotationRange: [0, 0],
        shape: 'circle',
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: [{
            {#name: 'Sam S Club',#}
            value: 10000,
            textStyle: {
                normal: {
                    color: 'black'
                },
                emphasis: {
                    color: 'red'
                }
            }
        }, {
            name: '自觉',
            value: 6181
        }, {
            name: '独立',
            value: 4386
        }, {
            name: '立法会补选',
            value: 4055
        }, {
            name: '香港独立',
            value: 2467
        }, {
            name: '和平占中',
            value: 2244
        }, {
            name: '雨伞运动',
            value: 1898
        }, {
            name: '言论自由',
            value: 1484
        }, {
            name: '民主',
            value: 1112
        }, {
            name: '选举',
            value: 965
        }, {
            name: '香港',
            value: 847
        }, {
            name: '缴械军队',
            value: 555
        }]
    }]
};
 myChart.setOption(option);
</script>
<script>
 var myChart = echarts.init(document.getElementById('main2'));
option = {
    title:{
        text:"词云图",
        x:'center',
    },
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 20,
        sizeRange: [12, 50],
        rotationRange: [0, 0],
        shape: 'circle',
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: [{
            {#name: 'Sam S Club',#}
            value: 10000,
            textStyle: {
                normal: {
                    color: 'black'
                },
                emphasis: {
                    color: 'red'
                }
            }
        }, {
            name: '自我发声',
            value: 3181
        }, {
            name: '民主自决',
            value: 7386
        }, {
            name: '立法会补选',
            value: 5055
        }, {
            name: '香港独立',
            value: 2467
        }, {
            name: '和平占中',
            value: 2244
        }, {
            name: '雨伞运动',
            value: 1898
        }, {
            name: '言论自由',
            value: 1484
        }, {
            name: '自由选举',
            value: 965
        }, {
            name: '香港自主',
            value: 3847
        }]
    }]
};
 myChart.setOption(option);
</script>
<script>
    var myChart = echarts.init(document.getElementById('main3'));
option = {
    title : {
        text: '图片、视频、文本所占比例',
        {#subtext: '纯属虚构',#}
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['视频','图片','文本']
    },
    series : [
        {
            name: '访问来源',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:10, name:'视频'},
                {value:22, name:'图片'},
                {value:23, name:'文本'},
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};
 myChart.setOption(option);
</script>
</html>

templates/sin_analysis.html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="">
{% load staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/main_demo.css' %}">
<title>天鹰监测系统</title>
</head>
<body>
<div style="width: 1300px;margin: auto;">
    <header style="background-color: #547ca5;height: 100px;vertical-align: center;">
        <img src="/static/img/eagle.jpg" height="100px" width="120px">
        <h2 style="text-align: center;margin-top: -60px;">天鹰监测系统</h2>
        <span style="position:relative;float: right;bottom: 30px;right: 20px;">
        <a href="#" style="color: black;" >{{ user.username }}<span class="caret"></span></a>
        <span ><a href="{% url 'socialNetworkCode:logout' %}" style="color: black;" >Logout</a></span>
        </span>
    </header>
        <br><br>
    <div class="navigate" style="float: left;background-color: #F9FAFB;">
        <ul class="">
            <li><a href="{% url 'socialNetworkCode:demo'  1 1 %}" ><b>信息概况监测</b></a></li>
            <h3 style="text-align: center;">{{ name }}</h3>
            <li><a href="{% url 'socialNetworkCode:peoplenews'  name  %}"  >人物介绍</a></li>
            <li><a href="{% url 'socialNetworkCode:all_analysis'  name  %}" >人物整体分析</a></li>
            <li><a href="{% url 'socialNetworkCode:sin_analysis'  name  %}" style="background-color:  #ecf5ff">人物单体分析</a></li>
        </ul>
    </div>
    <div class="content" style="float: left;margin-left: 20px;">
        <h3 >{{ name }}<img src="{% static user.photo %}" height="60px" width="100px" style="float: left;"></h3>
            <form>
                <br><br><b>标签：</b>
                {% for label in labels  %}
                    <input class="label" type="submit" name="name" value="{{ label.label }}" style="border: 1px solid #4183C4;margin-left:30px;padding: 2px 20px;background-color:white;border-radius: 8px;color: #4183C4;/">
                {% endfor %}
            </form>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">{{ name }}的相似人物</h3>
            <table class="table"  style="width: 900px;margin-left: 50px">
            <thead>
            <tr><th >相似人物</th>
                <th>相似度</th>
                </tr></thead>
                <tbody>
                {% for info in sim_people %}
                <tr>
            <td><a href="{% url 'socialNetworkCode:person_contrast' name info.similar_person %}">{{ info.similar_person }}</a></td>
                    <td>{{ info.similarity }}</td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">相关事件</h3>
            <table class="table"  style="width: 900px;margin-left: 50px">
            <thead>
            <tr><th >事件</th>
                <th>推文数量</th>
                <th>开始时间</th>
                <th>热度</th>
                </tr></thead>
                <tbody>
                {% for info in events %}
            <tr>
                <td><a href="{% url 'socialNetworkCode:person_event' info.sensitivevent name %}">{{ info.sensitivevent }}</a></td>
                <td>{{ info.tweetsnum }}</td>
                <td>{{ info.date }}</td>
                <td>{{ info.hot }}</td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        <h3 style="background-color: rgb(224, 224, 224);padding: 10px 30px;width: 1000px;">重点推文</h3>
            <table class="table"  style="width: 900px;margin-left: 50px">
            <thead>
            <tr><th >推文</th>
                <th>关键词</th>
                <th>时间</th>
                <th>警告度</th>
                </tr></thead>
                <tbody>
                {% for info in tweets %}
            <tr>
                <td><a href="{% url 'socialNetworkCode:person_tweet' info.idtweets  name %}">{{ info.tweets }}</a></td>
                <td>{{ info.keywords }}</td>
                <td>{{ info.time }}</td>
                <td>{{ info.warning }}</td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
    </div>
</div>

</body>
<script src="{% static 'js/echarts.js' %}"></script>
<script src="{% static 'js/jquery-2.1.0.js' %}"></script>
{#<script>#}
{#    $(document).ready(function () {#}
{#    $(".label").click(function () {#}
{#        $(this).css("background-color", "black").siblings().css("background-color","white");#}
{#        var label = $(this).text();#}
{#        console.log(label);#}
{#        $.ajax({#}
{#            //几个参数需要注意一下#}
{#                type: "POST",//方法类型#}
{#                dataType: "json",//预期服务器返回的数据类型#}
{#                url: "{% url 'socialNetworkCode:sin_analysis' name %}?label="+label//url#}
{#         });#}
{#    })})#}
{#</script>#}
{#为什么ajax不能返回html，感觉好奇怪啊。后台都能处理，就是不能显示html网页。#}
<script>
 $(document).ready(function () {
     var label = $('input').siblings();console.log(label);
     for (var i=0;i<label.length;i++){
        var x = input[i].value;

        if (x ==={{ label }}){
            $(this).css("background-color", "black").siblings().css("background-color","white");
        }
     }
 })
 
</script>
</html>